version: '3'
services:
  train:
    image: sheetalpattanaik/train:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 3

  movie:
    image: sheetalpattanaik/movie:v1
    ports:
      - "8002:80"
    deploy:
      replicas: 3

  recharge:
    image: sheetalpattanaik/recharge:v1
    ports:
      - "8003:80"
    deploy:
      replicas: 3

